Bump the frequenz-api-common package
frequenz-floss/frequenz-api-microgrid pull request #67
Opened 2023-06-06 12:54 UTC by leandro-lucarella-frequenz

The submodule was updated in a previous PR but the Python package was forgotten.

2023-06-06 12:55 UTC, tiyash-basu-frequenz requested changes
Needs a release note entry.

2023-06-07 08:11 UTC, tiyash-basu-frequenz commented
Dependabot created a duplicate PR: https://github.com/frequenz-floss/frequenz-api-microgrid/pull/68 :)

2023-06-07 10:37 UTC, leandro-lucarella-frequenz commented
Updated

2023-06-07 10:39 UTC, tiyash-basu-frequenz approved these changes

2023-06-07 10:39 UTC, merged