Revert "Update protobuf file headers"
frequenz-floss/frequenz-api-microgrid pull request #82
Opened 2023-08-04 15:14 UTC by llucax

The update was not necessary, as we want to keep the old format.

This reverts commit 5e1ce9972f827238bea65e0cd8908dc49529d46a.

2023-08-04 15:14 UTC, llucax commented
@thomas-nicolai-frequenz FYI

2023-08-04 17:57 UTC, tiyash-basu-frequenz requested changes
Could you please add an explanation for why the change was not necessary?

2023-08-05 07:44 UTC, llucax commented
Done in the pr description, will update the commit message on Monday.

2023-08-07 07:00 UTC, llucax commented
Updated the commit message too.

2023-08-07 07:38 UTC, tiyash-basu-frequenz approved these changes

2023-08-07 07:38 UTC, merged